# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Ummawellness
email: info@ummawellness.com
description: >- # this means to ignore newlines until "baseurl:"
  Your wellness journey starts here. Discover holistic health, mindfulness, and 
  sustainable living practices to nurture your mind, body, and spirit.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ummawellness.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ummawellness
github_username: ummawellness

# Chat widget configuration
chat:
  enabled: true
  bot_id: "754940" # Your unique chat ID from Intergram bot
  title_closed: "Chat with us!"
  title_open: "Ummawellness Support"
  intro_message: "Hi! How can we help you with your wellness journey?"
  auto_response: "Thank you for your message! We will get back to you soon."
  placeholder_text: "Type your message here..."
  main_color: "#a8d5a8"
  always_use_floating_button: true

# Build settings
theme: minima
plugins: []
collections:
  retreats:
    output: true
    permalink: /retreats/:name/

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
